"use client"

import * as React from "react"

type Language = "en" | "ja"

interface LanguageContextProps {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = React.createContext<LanguageContextProps>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
})

const enTranslations = {
  // Common
  "app.name": "TaskFlow",
  "app.tagline": "Streamline your workflow",
  "common.loading": "Loading...",
  "common.error": "Error",
  "common.success": "Success",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.back": "Back",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.logout": "Logout",
  "common.login": "Login",
  "common.register": "Register",
  "common.email": "Email",
  "common.password": "Password",
  "common.name": "Name",
  "common.submit": "Submit",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.sort": "Sort",
  "common.actions": "Actions",
  "common.status": "Status",
  "common.deadline": "Deadline",
  "common.progress": "Progress",
  "common.completed": "Completed",
  "common.inProgress": "In Progress",
  "common.notStarted": "Not started",
  "common.sections": "Sections",
  "common.tasks": "Tasks",
  "common.task": "Task",
  "common.noData": "No data available",
  "common.backToDashboard": "Back to Dashboard",
  "common.chooseFile": "Choose File",
  "common.noFileChosen": "No File Chosen",
  "common.uploadFile": "Upload File",
  "common.deleteFile": "Delete File",
  "common.viewFile": "View File",
  "common.downloadFile": "Download File",
  "common.fileUploaded": "File uploaded successfully",
  "common.fileDeleted": "File deleted successfully",
  "common.taskCompleted": "Task Completed",
  "common.taskIncomplete": "Mark Task as Incomplete",
  "common.taskCompletedMessage": "Great! Task has been marked as completed.",
  "common.taskIncompleteMessage": "Task has been marked as incomplete.",
  "common.returnToDashboard": "Return to Dashboard",
  "common.notFound": "Not Found",
  "common.notFoundMessage":
    "The resource you are looking for does not exist or you don't have permission to access it.",
  "common.users": "Users",
  "common.file": "File",
  "common.enter": "Enter",
  "common.pending": "Pending",
  "common.created": "Created",
  "common.unknown": "Unknown",
  "common.noFileUploaded": "No file uploaded",
  "common.notSet": "Not set",
  "common.continue": "Continue",
  "common.clickToDownload": "Click to download",
  "common.saving": "Saving...",
  "common.testConnection": "Test Connection",
  "common.debugInfo": "Debug Info",
  "common.view": "View",
  "common.from": "From",
  "common.lastMonth": "Last Month",
  "common.lastWeek": "Last Week",
  "common.newUser": "New User",
  "common.thisWeek": "This Week",
  "common.assignedTo": "Assigned To",
  "common.newMessage": "New Message",
  "common.messages": "Messages",
  "common.taskDeadline": "Deadline",
  "common.overdue": "Overdue",
  "common.approachingDeadlines": "Tasks with approaching deadlines",
  "common.deadlineApproaching": "Deadline approaching",

  // Task
  "task.messages": "Messages",
  "task.noMessages": "No messages yet. Start the conversation!",
  "task.typeMessage": "Type a message...",
  "task.newMessages": "New Messages",
  "task.waitingConfirmation": "Waiting for confirmation",
  "task.needsAttention": "Needs attention",
  "task.approved": "Approved",
  "task.refused": "Refused",
  "task.approve": "Approve",
  "task.refuse": "Refuse",
  "task.resetStatus": "Reset status",
  "task.taskApproved": "Task Approved",
  "task.taskRefused": "Task Refused",
  "task.statusReset": "Status Reset",
  "task.statusUpdated": "Task status has been updated successfully.",

  // Notification
  "notification.notifications": "Notifications",
  "notification.markAllAsRead": "Mark all as read",
  "notification.noNotifications": "No notifications",
  "notification.justNow": "Just now",
  "notification.minutesAgo": "minutes ago",
  "notification.hoursAgo": "hours ago",
  "notification.daysAgo": "days ago",
  "notification.dismissAll": "Dismiss All",
  "notification.newMessages": "New Messages",
  "notification.approachingDeadlines": "Approaching Deadlines",
  "notification.dismiss": "Dismiss",
  "notification.tasksNeedAttention": "Tasks That Need Attention",

  // Dashboard
  "dashboard.title": "Dashboard",
  "dashboard.welcome": "Welcome",
  "dashboard.actionFlows": "Action Flows",
  "dashboard.myFlows": "My Flows",
  "dashboard.recentActivity": "Recent Activity",
  "dashboard.upcomingDeadlines": "Upcoming Deadlines",
  "dashboard.createNew": "Create New",
  "dashboard.viewAll": "View All",
  "dashboard.adminDashboard": "Admin Dashboard",
  "dashboard.totalActionFlows": "Total Action Flows",
  "dashboard.completedFlows": "Completed Flows",
  "dashboard.activeUsers": "Active Users",
  "dashboard.recentActionFlows": "Recent Action Flows",

  // Action Flows
  "actionFlow.create": "Create Action Flow",
  "actionFlow.edit": "Edit Action Flow",
  "actionFlow.delete": "Delete Action Flow",
  "actionFlow.deleteConfirm": "Are you sure you want to delete this action flow?",
  "actionFlow.title": "Title",
  "actionFlow.titlePlaceholder": "e.g., Commuting Fee Application",
  "actionFlow.description": "Description",
  "actionFlow.descriptionPlaceholder": "Describe the purpose of this action flow",
  "actionFlow.deadline": "Deadline",
  "actionFlow.assignTo": "Assign To",
  "actionFlow.selectUser": "Select a user",
  "actionFlow.sections": "Sections",
  "actionFlow.addSection": "Add Section",
  "actionFlow.removeSection": "Remove Section",
  "actionFlow.sectionTitle": "Section Title",
  "actionFlow.tasks": "Tasks",
  "actionFlow.addTask": "Add Task",
  "actionFlow.removeTask": "Remove Task",
  "actionFlow.taskTitle": "Task Title",
  "actionFlow.taskDescription": "Task Description",
  "actionFlow.taskDescriptionPlaceholder": "Describe what the user needs to do",
  "actionFlow.inputs": "Input Fields",
  "actionFlow.addInput": "Add Input",
  "actionFlow.addTextInput": "Add Text Input",
  "actionFlow.addFileUpload": "Add File Upload",
  "actionFlow.removeInput": "Remove Input",
  "actionFlow.textFieldLabel": "Text field label",
  "actionFlow.fileUploadLabel": "File upload label",
  "actionFlow.inputLabel": "Input Label",
  "actionFlow.inputType": "Input Type",
  "actionFlow.inputTypeText": "Text",
  "actionFlow.inputTypeFile": "File",
  "actionFlow.preview": "Preview",
  "actionFlow.save": "Save Action Flow",
  "actionFlow.cancel": "Cancel",
  "actionFlow.notFound": "Action Flow Not Found",
  "actionFlow.notFoundMessage":
    "The action flow you are looking for does not exist or you don't have permission to access it.",
  "actionFlow.created": "Action flow created successfully",
  "actionFlow.updated": "Action flow updated successfully",
  "actionFlow.deleted": "Action flow deleted successfully",
  "actionFlow.progress": "Progress",
  "actionFlow.status": "Status",
  "actionFlow.details": "Details",
  "actionFlow.progressOverview": "Progress Overview",
  "actionFlow.totalSections": "Total Sections",
  "actionFlow.tasksCompleted": "Tasks Completed",
  "actionFlow.sectionsAndTasks": "Sections & Tasks",
  "actionFlow.noSections": "This action flow has no sections.",
  "actionFlow.noTasks": "This section has no tasks.",
  "actionFlow.uploadingFile": "Uploading file...",
  "actionFlow.uploadingFileMessage": "We are uploading your file",
  "actionFlow.unassigned": "Unassigned",
  "actionFlow.unknownUser": "Unknown User",
  "actionFlow.viewDetails": "View Details",
  "actionFlow.noTasksAssigned": "No tasks assigned yet",
  "actionFlow.noTasksAssignedMessage": "There are currently no tasks assigned to you.",
  "actionFlow.completed": "Action flow completed successfully",
  "actionFlow.chooseEmoji": "Choose an emoji",
  "actionFlow.createNew": "Create New Action Flow",
  "actionFlow.taskDeadline": "Task Deadline",
  "actionFlow.taskDeadlinePlaceholder": "Set a deadline for this task",
  chat: {
    assistant: "AI Assistant",
    typeMessage: "Type a message...",
    thinking: "Thinking...",
    openChat: "Open chat assistant",
  },
}

// Japanese translations - Placeholder translations, needs review
const jaTranslations = {
  // Common
  "app.name": "タスクフロー",
  "app.tagline": "ワークフローを効率化",
  "common.loading": "読み込み中...",
  "common.error": "エラー",
  "common.success": "成功",
  "common.save": "保存",
  "common.cancel": "キャンセル",
  "common.delete": "削除",
  "common.edit": "編集",
  "common.back": "戻る",
  "common.next": "次へ",
  "common.previous": "前へ",
  "common.logout": "ログアウト",
  "common.login": "ログイン",
  "common.register": "登録",
  "common.email": "メール",
  "common.password": "パスワード",
  "common.name": "名前",
  "common.submit": "送信",
  "common.search": "検索",
  "common.filter": "フィルター",
  "common.sort": "並べ替え",
  "common.actions": "アクション",
  "common.status": "ステータス",
  "common.deadline": "期限",
  "common.progress": "進捗",
  "common.completed": "完了",
  "common.inProgress": "進行中",
  "common.notStarted": "未開始",
  "common.sections": "セクション",
  "common.tasks": "タスク",
  "common.task": "タスク",
  "common.noData": "データがありません",
  "common.backToDashboard": "ダッシュボードに戻る",
  "common.chooseFile": "ファイルを選択",
  "common.noFileChosen": "ファイルが選択されていません",
  "common.uploadFile": "ファイルをアップロード",
  "common.deleteFile": "ファイルを削除",
  "common.viewFile": "ファイルを表示",
  "common.downloadFile": "ファイルをダウンロード",
  "common.fileUploaded": "ファイルが正常にアップロードされました",
  "common.fileDeleted": "ファイルが正常に削除されました",
  "common.taskCompleted": "タスク完了",
  "common.taskIncomplete": "タスクを未完了としてマーク",
  "common.taskCompletedMessage": "素晴らしい！タスクが完了としてマークされました。",
  "common.taskIncompleteMessage": "タスクが未完了としてマークされました。",
  "common.returnToDashboard": "ダッシュボードに戻る",
  "common.notFound": "見つかりません",
  "common.notFoundMessage": "お探しのリソースは存在しないか、アクセス権がありません。",
  "common.users": "ユーザー",
  "common.file": "ファイル",
  "common.enter": "入力",
  "common.pending": "保留中",
  "common.created": "作成日",
  "common.unknown": "不明",
  "common.noFileUploaded": "ファイルがアップロードされていません",
  "common.notSet": "未設定",
  "common.continue": "続ける",
  "common.clickToDownload": "クリックしてダウンロード",
  "common.saving": "保存中...",
  "common.testConnection": "接続テスト",
  "common.debugInfo": "デバッグ情報",
  "common.view": "表示",
  "common.from": "から",
  "common.lastMonth": "先月",
  "common.lastWeek": "先週",
  "common.newUser": "新規ユーザー",
  "common.thisWeek": "今週",
  "common.assignedTo": "担当者",
  "common.newMessage": "新着メッセージ",
  "common.messages": "メッセージ",
  "common.taskDeadline": "期限",
  "common.overdue": "期限超過",
  "common.approachingDeadlines": "期限が近いタスクがあります",
  "common.deadlineApproaching": "期限が近づいています",

  // Task
  "task.messages": "メッセージ",
  "task.noMessages": "まだメッセージはありません。会話を始めましょう！",
  "task.typeMessage": "メッセージを入力...",
  "task.newMessages": "新着メッセージ",
  "task.waitingConfirmation": "確認待ち",
  "task.needsAttention": "注意が必要",
  "task.approved": "承認済み",
  "task.refused": "拒否",
  "task.approve": "承認",
  "task.refuse": "拒否",
  "task.resetStatus": "状態をリセット",
  "task.taskApproved": "タスク承認",
  "task.taskRefused": "タスク拒否",
  "task.statusReset": "状態リセット",
  "task.statusUpdated": "タスクの状態が正常に更新されました。",

  // Notification
  "notification.notifications": "通知",
  "notification.markAllAsRead": "すべて既読にする",
  "notification.noNotifications": "通知はありません",
  "notification.justNow": "たった今",
  "notification.minutesAgo": "分前",
  "notification.hoursAgo": "時間前",
  "notification.daysAgo": "日前",
  "notification.dismissAll": "すべて消去",
  "notification.newMessages": "新着メッセージ",
  "notification.approachingDeadlines": "期限が近いタスク",
  "notification.dismiss": "消去",
  "notification.tasksNeedAttention": "注意が必要なタスク",

  // Dashboard
  "dashboard.title": "ダッシュボード",
  "dashboard.welcome": "ようこそ",
  "dashboard.actionFlows": "アクションフロー",
  "dashboard.myFlows": "マイフロー",
  "dashboard.recentActivity": "最近のアクティビティ",
  "dashboard.upcomingDeadlines": "今後の期限",
  "dashboard.createNew": "新規作成",
  "dashboard.viewAll": "すべて表示",
  "dashboard.adminDashboard": "管理者ダッシュボード",
  "dashboard.totalActionFlows": "アクションフロー合計",
  "dashboard.completedFlows": "完了したフロー",
  "dashboard.activeUsers": "アクティブユーザー",
  "dashboard.recentActionFlows": "最近のアクションフロー",

  // Action Flows
  "actionFlow.create": "アクションフロー作成",
  "actionFlow.edit": "アクションフロー編集",
  "actionFlow.delete": "アクションフロー削除",
  "actionFlow.deleteConfirm": "このアクションフローを削除してもよろしいですか？",
  "actionFlow.title": "タイトル",
  "actionFlow.titlePlaceholder": "例：通勤費申請",
  "actionFlow.description": "説明",
  "actionFlow.descriptionPlaceholder": "このアクションフローの目的を説明してください",
  "actionFlow.deadline": "期限",
  "actionFlow.assignTo": "割り当て先",
  "actionFlow.selectUser": "ユーザーを選択",
  "actionFlow.sections": "セクション",
  "actionFlow.addSection": "セクション追加",
  "actionFlow.removeSection": "セクション削除",
  "actionFlow.sectionTitle": "セクションタイトル",
  "actionFlow.tasks": "タスク",
  "actionFlow.addTask": "タスク追加",
  "actionFlow.removeTask": "タスク削除",
  "actionFlow.taskTitle": "タスクタイトル",
  "actionFlow.taskDescription": "タスク説明",
  "actionFlow.taskDescriptionPlaceholder": "ユーザーが何をすべきか説明してください",
  "actionFlow.inputs": "入力項目",
  "actionFlow.addInput": "入力項目追加",
  "actionFlow.addTextInput": "テキスト入力追加",
  "actionFlow.addFileUpload": "ファイルアップロード追加",
  "actionFlow.removeInput": "入力項目削除",
  "actionFlow.textFieldLabel": "テキストフィールドラベル",
  "actionFlow.fileUploadLabel": "ファイルアップロードラベル",
  "actionFlow.inputLabel": "入力ラベル",
  "actionFlow.inputType": "入力タイプ",
  "actionFlow.inputTypeText": "テキスト",
  "actionFlow.inputTypeFile": "ファイル",
  "actionFlow.preview": "プレビュー",
  "actionFlow.save": "アクションフロー保存",
  "actionFlow.cancel": "キャンセル",
  "actionFlow.notFound": "アクションフローが見つかりません",
  "actionFlow.notFoundMessage": "お探しのアクションフローは存在しないか、アクセス権がありません。",
  "actionFlow.created": "アクションフローが作成されました",
  "actionFlow.updated": "アクションフローが更新されました",
  "actionFlow.deleted": "アクションフローが削除されました",
  "actionFlow.progress": "進捗",
  "actionFlow.status": "ステータス",
  "actionFlow.details": "詳細",
  "actionFlow.progressOverview": "進捗概要",
  "actionFlow.totalSections": "セクション合計",
  "actionFlow.tasksCompleted": "完了タスク",
  "actionFlow.sectionsAndTasks": "セクションとタスク",
  "actionFlow.noSections": "このアクションフローにはセクションがありません。",
  "actionFlow.noTasks": "このセクションにはタスクがありません。",
  "actionFlow.uploadingFile": "アップロード中...",
  "actionFlow.uploadingFileMessage": "ファイルをアップロードしています",
  "actionFlow.unassigned": "未割り当て",
  "actionFlow.unknownUser": "不明なユーザー",
  "actionFlow.viewDetails": "詳細を表示",
  "actionFlow.noTasksAssigned": "まだタスクが割り当てられていません",
  "actionFlow.noTasksAssignedMessage": "現在、あなたに割り当てられているタスクはありません。",
  "actionFlow.completed": "アクションフローが正常に完了しました",
  "actionFlow.chooseEmoji": "絵文字を選択",
  "actionFlow.createNew": "新規アクションフロー作成",
  "actionFlow.taskDeadline": "タスク期限",
  "actionFlow.taskDeadlinePlaceholder": "このタスクの期限を設定",
}

function getTranslations(language: Language) {
  return language === "en" ? enTranslations : jaTranslations
}

function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<Language>("en")

  const t = React.useCallback(
    (key: string) => {
      const translations = getTranslations(language)
      return translations[key] || key
    },
    [language],
  )

  const value = React.useMemo(
    () => ({
      language,
      setLanguage,
      t,
    }),
    [language, setLanguage, t],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

function useLanguage() {
  const context = React.useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { LanguageProvider, useLanguage }
